[workspace]
resolver = "2"
members = ["rc-zip-cli", "rc-zip", "rc-zip-sync", "rc-zip-tokio", "ziplinter"]
exclude = ["fuzz"]

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
