name: test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install Rust specified toolchain
        run: rustup show
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Run cargo clippy
        run: |
          cargo clippy --all-targets -- -D warnings
      - name: Run cargo nextest
        run: |
          cargo nextest run --profile ci --all-features

  test-maturin-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Rust
        run: rustup show

      - name: Install Maturin
        run: pip install maturin

      - name: Create and activate virtualenv
        working-directory: "ziplinter-python"
        run: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -U pip maturin
            pip freeze

      - name: Build the Python module
        working-directory: "ziplinter-python"
        run: |
          source .venv/bin/activate
          maturin develop

      - name: Run test script
        working-directory: "ziplinter-python"
        run: |
          source .venv/bin/activate
          python test.py
